/** @type {import('tailwindcss').Config} */
export default {
  content: ["index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      sm: "0px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
    extend: {
      spacing: {
        "1/5": "20.0%",
        "1/6": "16.7%",
        "1/8": "12.5%",
        "5/8": "62.5%",
        "7/8": "87.5%",
        "1/10": "10.0%",
        "1/16": "6.25%",
        "1/24": "4.17%",
        "29/40": "72.5%",
        "5/200": "2.5%",
        100: "25rem",
        200: "50rem",
      },
      fontFamily: {
        jetbrains: ["Jetbrains Mono"],
      },
    },
  },
  plugins: [
    require("tailwindcss-themer")({
      themes: [
        {
          name: "light",
          extend: {
            colors: {
              ovr: "hsl(0, 0%, 98%)",
              text: "hsl(0, 0%, 18%)",
              placeholder: "hsl(0, 0%, 58%)",
              slider: "hsl(0, 0%, 70%)",
              block: "hsl(0, 0%, 95%)",
              border: "hsl(0, 0%, 85%)",
              "current-nodes": "hsl(50, 20%, 75%)",
              "slider-thumb": "hsl(30, 30%, 60%)",
              "border-active": "hsl(50, 40%, 65%)",
              "border-hover": "hsl(50, 5%, 78%)",
              "toggle-circle": "hsl(0, 0%, 97%)",
              "toggle-uncheck": "hsl(50, 15%, 60%)",
              "toggle-hover": "hsl(50, 10%, 55%)",
              "toggle-check": "hsl(50, 10%, 40%)",
              selected: "hsl(30, 65%, 45%)",
              "format-ok": "hsl(150, 45%, 60%)",
              "format-ok-border": "hsl(150, 40%, 50%)",
              "format-ok-hover": "hsl(150, 50%, 70%)",
              "format-ok-active": "hsl(150, 35%, 85%)",
              "format-bad": "hsl(10, 45%, 55%)",
              "format-bad-border": "hsl(10, 40%, 45%)",
              "format-bad-active": "hsl(10, 35%, 35%)",
              "clear-normal": "hsl(40, 35%, 55%)",
              "clear-hover": "hsl(40, 35%, 70%)",
              "clear-active": "hsl(40, 35%, 80%)",
              shadow: "hsl(0, 0%, 95%)",
              "tab-hover": "hsl(40, 0%, 92%)",
              "tab-active": "hsl(40, 0%, 85%)",
              "palette-base": "#f4f4f4",
              "palette-yellow": "#e8c76f",
              "palette-yellow-dull": "#e0b45d",
              "palette-lemon": "#dedf73",
              "palette-lemon-dull": "#c5c760",
              "palette-lime": "#bede7e",
              "palette-lime-dull": "#acd96c",
              "palette-green": "#89da81",
              "palette-green-dull": "#7bc971",
              "palette-wood": "#91c4a2",
              "palette-wood-dull": "#7fb292",
              "palette-teal": "#89caca",
              "palette-teal-dull": "#77b8b8",
              "palette-azure": "#89b4da",
              "palette-azure-dull": "#7ca1cb",
              "palette-sea": "#8aa2da",
              "palette-sea-dull": "#7992cb",
              "palette-blue": "#698bda",
              "palette-blue-dull": "#5f78cb",
              "palette-flower": "#7685e0",
              "palette-flower-dull": "#6775d2",
              "palette-purple": "#7d82e0",
              "palette-purple-dull": "#6f74d2",
              "palette-violet": "#8d7fe0",
              "palette-violet-dull": "#7c70d2",
              "palette-grape": "#9b7ee0",
              "palette-grape-dull": "#8a6fd0",
              "palette-pink": "#ab7ed2",
              "palette-pink-dull": "#9a6ec2",
              "palette-sakura": "#bb7ec0",
              "palette-sakura-dull": "#a96db2",
              "palette-flesh": "#c27ea2",
              "palette-flesh-dull": "#b06d92",
              "palette-raw": "#c07e8a",
              "palette-raw-dull": "#a96f7a",
              "palette-orange": "#d68b65",
              "palette-orange-dull": "#c67850",
              "palette-moon": "#d9a769",
              "palette-moon-dull": "#c48d55",
            },
          },
        },
        {
          name: "dark",
          extend: {
            colors: {
              ovr: "hsl(0, 0%, 14%)",
              text: "hsl(0, 0%, 88%)",
              placeholder: "hsl(0, 0%, 48%)",
              slider: "hsl(0, 0%, 38%)",
              block: "hsl(0, 0%, 16%)",
              border: "hsl(0, 0%, 30%)",
              "current-nodes": "hsl(50, 15%, 45%)",
              "slider-thumb": "hsl(30, 30%, 50%)",
              "border-active": "hsl(50, 40%, 30%)",
              "border-hover": "hsl(50, 5%, 40%)",
              "toggle-circle": "hsl(0, 0%, 25%)",
              "toggle-uncheck": "hsl(50, 10%, 45%)",
              "toggle-hover": "hsl(50, 10%, 65%)",
              "toggle-check": "hsl(50, 10%, 75%)",
              selected: "hsl(30, 55%, 70%)",
              "format-ok": "hsl(150, 35%, 30%)",
              "format-ok-border": "hsl(150, 35%, 35%)",
              "format-ok-hover": "hsl(150, 35%, 40%)",
              "format-ok-active": "hsl(150, 35%, 55%)",
              "format-bad": "hsl(10, 35%, 30%)",
              "format-bad-border": "hsl(10, 35%, 50%)",
              "format-bad-active": "hsl(10, 35%, 70%)",
              "clear-normal": "hsl(40, 35%, 30%)",
              "clear-hover": "hsl(40, 35%, 35%)",
              "clear-active": "hsl(40, 35%, 45%)",
              shadow: "hsl(0, 0%, 16%)",
              "tab-hover": "hsl(40, 0%, 15%)",
              "tab-active": "hsl(40, 0%, 20%)",
              "palette-base": "#333333",
              "palette-yellow": "#907d12",
              "palette-yellow-dull": "#806a00",
              "palette-lemon": "#707220",
              "palette-lemon-dull": "#505e02",
              "palette-lime": "#5a7e1e",
              "palette-lime-dull": "#3b5e0e",
              "palette-green": "#39731e",
              "palette-green-dull": "#1d530e",
              "palette-wood": "#49705e",
              "palette-wood-dull": "#325344",
              "palette-teal": "#49706c",
              "palette-teal-dull": "#2f5555",
              "palette-azure": "#416a8a",
              "palette-azure-dull": "#315a7a",
              "palette-sea": "#405a8a",
              "palette-sea-dull": "#314a7a",
              "palette-blue": "#3050aa",
              "palette-blue-dull": "#2b408c",
              "palette-flower": "#4145b0",
              "palette-flower-dull": "#2f3491",
              "palette-purple": "#4e44b0",
              "palette-purple-dull": "#3d3491",
              "palette-violet": "#5a40b0",
              "palette-violet-dull": "#493491",
              "palette-grape": "#653bb0",
              "palette-grape-dull": "#533091",
              "palette-pink": "#8036a0",
              "palette-pink-dull": "#602f80",
              "palette-sakura": "#98358e",
              "palette-sakura-dull": "#7a2b70",
              "palette-flesh": "#a0356e",
              "palette-flesh-dull": "#802b55",
              "palette-raw": "#a03550",
              "palette-raw-dull": "#802b40",
              "palette-orange": "#b0502f",
              "palette-orange-dull": "#903a10",
              "palette-moon": "#b07020",
              "palette-moon-dull": "#904f10",
            },
          },
        },
      ],
    }),
  ],
};
